apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvYWNjZXNzLXRva2VuIjoge30sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxL3JlZnJlc2gtdG9rZW4iOiB7fSwKCQkibmV4dXMuYXZvc2VuZC50ZWNoIjoge30sCgkJImdoY3IuaW8iOnsKCQkJImF1dGgiOiAiZVhWeWRHRmxkblIyT21kcGRHaDFZbDl3WVhSZk1URkJUa0pXUjBSSk1FOUJTVFJTWTJwdWNrSndhRjlvZEVKV05XRlZWM2szVVhCcFoyVlViWGx6ZVVaUWVISnJPRWhPZVcxTVJYVldOM1p5WW5CVFRFNXVTVlpQVVVrMlJFd3dOak50YURWYVN3PT0ifQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9LAoJCSJkZWJ1ZyI6IHsKCQkJImhvb2tzIjogImV4ZWMiCgkJfSwKCQkic2NvdXQiOiB7CgkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9Cg==
type: kubernetes.io/dockerconfigjson
